CREATE DATABASE PCCLINICS;
USE PCCLINICS;

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY
	,RazaoSocial VARCHAR (100) NOT NULL
	,CNPJ VARCHAR (50) NOT NULL
	,Endereco VARCHAR (15) NOT NULL
);

CREATE TABLE Dono
(
	IdDono INT PRIMARY KEY IDENTITY
	,Dono VARCHAR (50) NOT NULL
);

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY
	,IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica)
	,Veterinario VARCHAR (100) NOT NULL
	,CRM CHAR (7) NOT NULL
);

CREATE TABLE TipoPet
(
	IdTipoPet INT PRIMARY KEY IDENTITY
	,Tipo VARCHAR (100) NOT NULL
);

CREATE TABLE Raca 
(
	IdRaca INT PRIMARY KEY IDENTITY
	,IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet)
	,Raca VARCHAR(40) NOT NULL
);

CREATE TABLE Pet
(
	IdPet INT PRIMARY KEY IDENTITY
	,IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca)
	,IdDono INT FOREIGN KEY REFERENCES Dono (IdDono)	
	,NomePet VARCHAR (20) NOT NULL
	,DataNascimento DATE NOT NULL
);

CREATE TABLE Atendimento
(
	IdAtendimento INT PRIMARY KEY IDENTITY
	,IdPet INT FOREIGN KEY REFERENCES Pet (IdPet)
	,IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario)
	,DataAtendimento DATE NOT NULL
	,Descricao VARCHAR(200) NOT NULL
);

